receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: apisix
          scrape_interval: 15s
          metrics_path: /apisix/prometheus/metrics
          static_configs:
            - targets: ["apisix:9091"]

processors:
  memory_limiter:
    limit_mib: 256
    check_interval: 1s
  batch:
    send_batch_size: 500
    timeout: 5s

exporters:
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  prometheusremotewrite:
    endpoint: "http://thanos-receive:19291/api/v1/receive"
    resource_to_telemetry_conversion:
      enabled: true

service:
  telemetry:
    logs:
      level: warn

  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite]
