apiVersion: 1

datasources:
  - name: Thanos
    uid: thanos
    type: prometheus
    access: proxy
    url: http://thanos-query:10902
    isDefault: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToMetricsV2:
        datasourceUid: thanos
        customQuery: false
        tags:
          - key: service.name
            value: job
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: false
      serviceMap:
        datasourceUid: thanos
      nodeGraph:
        enabled: true
      search:
        hide: false
      traceQuery:
        timeShiftEnabled: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      derivedFields:
        # extract trace_id from zerolog JSON and link to Tempo
        - name: TraceID
          matcherRegex: '"trace_id"\s*:\s*"([a-f0-9]{32})"'
          url: '$${__value.raw}'
          datasourceUid: tempo
          urlDisplayLabel: View trace
